language: ruby
rvm:
  - 2.5.0
cache: bundler
branches:
  only:
  - gh-pages
script:
  - echo "Building Site"
  - bundle exec "jekyll build --profile"
  - echo "Testing Site"
  - bundle exec htmlproofer ./_site --disable-external --check-html --assume-extension --allow-hash-href
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
